spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: http://localhost:3306/springcloud?characterEncoding=utf-8&iseSSL=false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8777
